routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/','Auth\LoginController@showLoginForm');
//language
Route::get('lang/{locale}', 'LocalizationController@index')->name('lang');

Route::middleware('auth')->group(function () {
  Route::get('dashboard','MainController@dashboard')->name('dashboard');

  Route::get('getways', 'MainController@getways')->name('getways');
  
  Route::prefix('settings')->group(function () {
    // Settings => (cities, townships, statuses, expense_types, payment_types, banks)
    Route::resource('cities','CityController');
    Route::resource('townships','TownshipController');
    Route::resource('statuses','StatusController');
    Route::resource('expense_types','ExpenseTypeController');
    Route::resource('payment_types','PaymentTypeController');
    Route::resource('banks','BankController');
    Route::resource('sendergate','SenderGateController'); 
    Route::resource('senderoffice','SenderOfficeController');
  });

Route::post('expensebytype','ExpenseController@expensebytype')->name('expensebytype');
  // Success List
  Route::get('success_list','MainController@success_list')->name('success_list');

  // Reject List
  Route::get('reject_list','MainController@reject_list')->name('reject_list');
  Route::post('rejectitem','MainController@rejectitem')->name('rejectitem');


  // Return List
  Route::get('return_list','MainController@return_list')->name('return_list');
  Route::post('returnitem','MainController@returnitem')->name('returnitem');

  // Delay List
  Route::get('delay_list','MainController@delay_list')->name('delay_list');
  Route::get('delaycount','MainController@delaycount')->name('delaycount');

  // Financial Statement
  Route::get('statements','MainController@financial_statements')->name('statements');

  Route::post('successreport','MainController@successreport')->name('successreport');

  // Debt List
  Route::get('debt_list','MainController@debt_list')->name('debt_list');
  Route::get('debt_history','MainController@debt_history')->name('debt_history');

  Route::get('way_history','MainController@way_history')->name('way_history');
  Route::get('pickup_history','MainController@pickup_history')->name('pickup_history');
  Route::get('historydetails/{id}','MainController@historydetails')->name('historydetails');

  Route::get('debit/getdebitlistbyclient/{id}', 'MainController@getdebitlistbyclient')->name('debit.getdebitlistbyclient');
  Route::post('debit/getdebithistorybyclient', 'MainController@getdebithistorybyclient')->name('debit.getdebithistorybyclient');

  Route::post('getwayhistory','MainController@getwayhistory')->name('getwayhistory');
  Route::post('pickupbyclient','MainController@pickupbyclient')->name('pickupbyclient');
  Route::post('fix_debit', 'MainController@fix_debit')->name('fix_debit');

  Route::post('updateincome','MainController@updateincome')->name('updateincome');
  Route::post('incomesearch','MainController@incomesearch')->name('incomesearch');
  Route::post('waysreport','MainController@waysreport')->name('waysreport');
  Route::post('expensesearch','MainController@expensesearch')->name('expensesearch');
  Route::post('profit','MainController@profit')->name('profit');
  Route::get('banktransfer','MainController@banktransfer')->name('banktransfer');
  Route::post('transfer','MainController@transfer')->name('transfer.store');
  //pickupdone by delivery man
  Route::get('pickupdone/{id}/{qty}','MainController@pickupdone')->name('pickupdone');

  //amounta ad qty edit
  Route::post('editamountandqty','MainController@editamountandqty')->name('editamountandqty');

//normal
  Route::get('normal/{id}','MainController@normal')->name('normal');
  // staff
  Route::resource('staff','StaffController');

  //  For Staff


  // get schedules
  Route::resource('schedules', 'ScheduleController');
  // get assigned pickup
  Route::get('allpickup','ScheduleController@allpickup')->name('allpickup');
  // get assigned pickup noti
  Route::get('getnoti','ScheduleController@getnoti')->name('getnoti');


  // client
  Route::get('cancel', 'MainController@cancel')->name('cancel.index');
  Route::post('uploadfile', 'ScheduleController@uploadfile')->name('uploadfile');
  Route::post('storeandassignschedule', 'ScheduleController@storeandassignschedule')->name('schedules.storeandassign');

  Route::resource('items', 'ItemController');
  Route::get('newitem','ItemController@newitem')->name('newitem');
  Route::get('onway','ItemController@onway')->name('onway');
  Route::get('items/collectitem/{cid}/{pid}','ItemController@collectitem')->name('items.collect');
  Route::post('itemdetail','ItemController@itemdetail')->name('itemdetail');
  Route::post('wayassign','ItemController@assignWays')->name('wayassign');

  Route::get('checkitem/{pickupid}','ItemController@checkitem')->name('checkitem');
  Route::post('updateamount','ItemController@updateamount')->name('updateamount');
  
  Route::get('rejectnoti','MainController@rejectnoti')->name('rejectnoti');
  Route::get('clearrejectnoti/{id}','MainController@clearrejectnoti')->name('clearrejectnoti');
  Route::get('seennoti','MainController@seennoti')->name('seennoti');
  Route::post('updatewayassign','ItemController@updatewayassign')->name('updatewayassign');
  Route::post('townshipbystatus','ItemController@townshipbystatus')->name('townshipbystatus');
  Route::get('deletewayassign/{id}','ItemController@deletewayassign')->name('deletewayassign');


  Route::resource('clients', 'ClientController');
  Route::resource('delivery_men', 'DeliveryMenController');

  Route::get('incomes', 'MainController@incomes')->name('incomes');
  Route::get('incomes/addincomes', 'MainController@addincomeform')->name('incomes.create');
  Route::get('incomes/getsuccesswaysbydeliveryman/{id}', 'MainController@successways')->name('incomes.successways');
  Route::post('incomes/addincomes', 'MainController@addincomes')->name('incomes.store');
  Route::post('getitembyway', 'MainController@getitembyway')->name('getitembyway');
  Route::resource('expenses','ExpenseController');

  // For Client
  Route::get('pickups','MainController@pickups')->name('pickups');
  Route::post('pickups','MainController@donepickups')->name('donepickups');
  Route::post('delichargebytown','ItemController@delichargebytown')->name('delichargebytown');
  // Route::get('ways','MainController@ways')->name('ways');

  Route::prefix('ways')->group(function () {
    Route::get('pending','MainController@pending_ways')->name('pending_ways');
    Route::post('pending_deli_date','MainController@pending_deli_date')->name('pending_deli_date');
    Route::post('success_deli_date','MainController@success_deli_date')->name('success_deli_date');
    Route::post('reject_deli_date','MainController@reject_deli_date')->name('reject_deli_date');
    Route::get('reject','MainController@rejectwaybydeliveryman')->name('rejectwaybydeliveryman');
    Route::get('success','MainController@success_ways')->name('success_ways');
  });

  Route::post('waybydeliveryman','MainController@waybydeliveryman')->name('waybydeliveryman');
  Route::post('/createpdf', 'MainController@createpdf')->name('createpdf');

  Route::post('makeDelivered','MainController@makeDeliver')->name('makeDeliver');
  Route::post('retuenDeliver','MainController@retuenDeliver')->name('retuenDeliver');
  Route::post('rejectDeliver','MainController@rejectDeliver')->name('rejectDeliver');
  

});

Route::resource('profiles','ProfileController');

Auth::routes(['register'=>false]);

Route::get('/home', 'HomeController@index')->name('home');

app/Expense.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
class Expense extends Model
{
  use SoftDeletes;
	protected $fillable=[
  	'amount', 'description', 'expense_type_id' , 'status', 'pickup_id', 'staff_id', 'city_id', 'item_id'
  ];

  public function expense_type()
  {
    return $this->belongsTo('App\ExpenseType');
  }

  public function pickup()
  {
    return $this->belongsTo('App\Pickup');
  }

  public function staff()
  {
    return $this->belongsTo('App\Staff');
  }

  public function city()
  {
    return $this->belongsTo('App\City');
  }

  public function item()
  {
    return $this->belongsTo('App\Item');
  }

  public function transaction()
  {
    return $this->hasOne('App\Transaction');
  }
}

app/ExpenseType.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
class ExpenseType extends Model
{
	use SoftDeletes;
  protected $fillable=[
  	'name'
  ];

  public function expenses()
  {
    return $this->hasMany('App\Expense');
  }
}

app/Http/Controllers/ExpenseController.php
<?php

namespace App\Http\Controllers;

use App\Expense;
use App\ExpenseType;
use Illuminate\Http\Request;
use Auth;
use App\Bank;
use App\Transaction;
use Yajra\DataTables\Facades\DataTables;

class ExpenseController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
         $expensetypes=ExpenseType::all();
         $expenses=Expense::orderBy('id','desc')
                            // ->where('status',1)
                            ->get();
       
        return view('expense.index',compact('expensetypes','expenses'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $expensetypes=ExpenseType::all();
         $banks=Bank::all();
        return view('expense.create',compact('expensetypes','banks'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validator = $request->validate([
            'description'  => ['required', 'string', 'max:255'],
            'expensetype'=>['required'],
            'amount'=>['required'],
            'bank'=>['required']
        ]);

        if($validator){
            

            $bank= Bank::find($request->bank);
            if($request->amount <= $bank->amount){
            $expense=new Expense;
            $expense->description=$request->description;
            $expense->amount=$request->amount;
            $expense->expense_type_id=$request->expensetype;
            $expense->staff_id = Auth::user()->staff->id;
            $expense->city_id = 1; // default yangon
            $expense->status = 1;
            $expense->save();
            $bank->amount=$bank->amount-$request->amount;
            $bank->save();
            $transaction=new Transaction;
            $transaction->bank_id=$request->bank;
            $transaction->expense_id=$expense->id;
            $transaction->amount=$request->amount;
            $transaction->description=$request->description;
            $transaction->save();
             return redirect()->route('expenses.index')->with("successMsg",'New Expense is ADDED in your data');
            }else{
                return redirect()->route('expenses.index')->with("successMsg",'New Expense added is not successfully.Try again!');
            }
           
        }
        else
        {
            return redirect::back()->withErrors($validator);
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Expense  $expense
     * @return \Illuminate\Http\Response
     */
    public function show(Expense $expense)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Expense  $expense
     * @return \Illuminate\Http\Response
     */
    public function edit(Expense $expense)
    {
        $expensetypes=ExpenseType::all();
        $expense=$expense;
         $banks=Bank::all();
        return view('expense.edit',compact('expense','expensetypes','banks'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Expense  $expense
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Expense $expense)
    {
        $validator = $request->validate([
            'description'  => ['required', 'string', 'max:255'],
            'expensetype'=>['required'],
            'amount'=>['required'],
            'bank'=>['required']
        ]);

        if($validator){
            $bank= Bank::find($request->bank);
            if($request->amount <= $bank->amount){
            $expense=$expense;
            $expense->description=$request->description;
            $expense->amount=$request->amount;
            $expense->expense_type_id=$request->expensetype;
            $expense->save();

            $oldbank=Bank::find($expense->transaction->bank_id);
            $oldbank->amount=$oldbank->amount+$expense->transaction->amount;
            $oldbank->save();

            $bank->amount=$bank->amount-$request->amount;
            $bank->save();
            $transaction=Transaction::where('bank_id',$expense->transaction->bank_id)->first();
            $transaction->bank_id=$request->bank;
            $transaction->expense_id=$expense->id;
            $transaction->amount=$request->amount;
            $transaction->description=$request->description;
            $transaction->save();
            return redirect()->route('expenses.index')->with("successMsg",'New Expense updated successfully');
            }
           
        }
        else
        {
            return redirect::back()->withErrors($validator);
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Expense  $expense
     * @return \Illuminate\Http\Response
     */
    public function destroy(Expense $expense)
    {
        $expense=$expense;
        $expense->delete();
        return redirect()->route('expenses.index')->with('successMsg','Existing Expense is DELETED in your data');
    }

    public function expensebytype(Request $request){
        $sdate = $request->sdate;
        $edate = $request->edate;
        $type_id=$request->type_id;
        $expenses="";
       
        if($type_id==null){
            $expenses=Expense::whereBetween('created_at', [$sdate.' 00:00:00',$edate.' 23:59:59'])
                            // ->where('status',1)
                            ->orderBy('id','desc')
                            ->with('expense_type')
                            ->get();
        }else if($sdate==null && $edate==null){
            $expenses=Expense::where('expense_type_id',$type_id)
                            // ->where('status',1)
                            ->orderBy('id','desc')
                            ->with('expense_type')
                            ->get();
        }else{
            $expenses=Expense::whereBetween('created_at', [$sdate.' 00:00:00',$edate.' 23:59:59'])
                                ->where('expense_type_id',$type_id)
                                // ->where('status',1)
                                ->orderBy('id','desc')
                                ->with('expense_type')
                                ->get();
        }
        
        return Datatables::of($expenses)->addIndexColumn()->toJson();
    }
}

resources/views/expense/create.blade.php
@extends('main')
@section('content')
  <main class="app-content">
    <div class="app-title">
      <div>
        <h1><i class="fa fa-dashboard"></i> {{ __("Expenses")}}</h1>
        <!-- <p>A free and open source Bootstrap 4 admin template</p> -->
      </div>
      <ul class="app-breadcrumb breadcrumb">
        <li class="breadcrumb-item"><i class="fa fa-home fa-lg"></i></li>
        <li class="breadcrumb-item"><a href="{{route('expenses.index')}}">{{ __("Expenses")}}</a></li>
      </ul>
    </div>
    <div class="row">
      <div class="col-md-12">
        <div class="tile">
          <h3 class="tile-title d-inline-block">Expense Create Form</h3>
          
          <form action="{{route('expenses.store')}}" method="POST">
            @csrf
            <div class="form-group">
              <label for="description">{{ __("Description")}}:</label>
              <textarea class="form-control" id="description" name="description"type="text" placeholder="Enter description"></textarea>
              <div class="form-control-feedback text-danger"> {{$errors->first('description') }} </div>
            </div>

            <div class="form-group">
              <label for="amount">{{ __("Amount")}}:</label>
              <input class="form-control" id="amount" name="amount" type="number" placeholder="Enter amount">
              <div class="form-control-feedback text-danger"> {{$errors->first('amount') }} </div>
            </div>

            <div class="form-group">
              <label for="expensetype">{{ __("Expense Types")}}</label>
              <select class="form-control" id="expensetype" name="expensetype">
                <option>Choose Expense Type</option>
                @foreach($expensetypes as $row)
                <option value="{{$row->id}}">{{$row->name}}</option>
                @endforeach
              </select>
              <div class="form-control-feedback text-danger"> {{$errors->first('expensetype') }} </div>
            </div>

              <div class="form-group cityname">
              <label for="bank">{{ __("Banks")}}:</label>
              <select class="form-control" id="bank" name="bank">
                <option value="">Choose Bank</option>
                @foreach($banks as $row)
                <option value="{{$row->id}}">{{$row->name}}({{$row->amount}})</option>
                @endforeach
              </select>
              <div class="form-control-feedback text-danger"> {{$errors->first('bank') }} </div>
            </div>

            <div class="form-group">
              <button class="btn btn-primary" type="submit">{{ __("Save")}}</button>
            </div>
          </form>
        </div>
      </div>
      
    </div>
  </main>
@endsection 

resources/views/expense/edit.blade.php
@extends('main')
@section('content')
  <main class="app-content">
    <div class="app-title">
      <div>
        <h1><i class="fa fa-dashboard"></i> {{ __("Expenses")}} </h1>
        <!-- <p>A free and open source Bootstrap 4 admin template</p> -->
      </div>
      <ul class="app-breadcrumb breadcrumb">
        <li class="breadcrumb-item"><i class="fa fa-home fa-lg"></i></li>
        <li class="breadcrumb-item"><a href="{{route('expenses.index')}}">{{ __("Expenses")}}</a></li>
      </ul>
    </div>
    <div class="row">
      <div class="col-md-12">
        <div class="tile">
          <h3 class="tile-title d-inline-block">Expense Edit Form</h3>
          
          <form action="{{route('expenses.update',$expense->id)}}" method="POST">
            @csrf
            @method('put')
          <div class="form-group">
              <label for="description">{{ __("Description")}}:</label>
              <textarea class="form-control" id="description" name="description"type="text" placeholder="Enter description">{{$expense->description}}</textarea>
              <div class="form-control-feedback text-danger"> {{$errors->first('description') }} </div>
            </div>

            <div class="form-group">
              <label for="amount">{{ __("Amount")}}:</label>
              <input class="form-control" id="amount" name="amount" type="number" placeholder="Enter amount" value="{{$expense->amount}}">
              <div class="form-control-feedback text-danger"> {{$errors->first('amount') }} </div>
            </div>

            <div class="form-group">
              <label for="expensetype">{{ __("Expense Types")}}</label>
              <select class="form-control" id="expensetype" name="expensetype">
                <option>Choose Expense Type</option>
                @foreach($expensetypes as $row)
                <option value="{{$row->id}}"  @if($expense->expense_type_id==$row->id) selected @endif>{{$row->name}}</option>
                @endforeach
              </select>
              <div class="form-control-feedback text-danger"> {{$errors->first('expensetype') }} </div>
            </div>


             <div class="form-group cityname">
              <label for="bank">{{ __("Banks")}}:</label>
              <select class="form-control" id="bank" name="bank">
                <option value="">Choose Bank</option>
                @foreach($banks as $row)
                <option value="{{$row->id}}" @if(isset($expense->transaction) && ($row->id == $expense->transaction->bank_id)) {{'selected'}} @endif>{{$row->name}}({{$row->amount}})</option>
                @endforeach
              </select>
              <div class="form-control-feedback text-danger"> {{$errors->first('bank') }} </div>
            </div>

            <div class="form-group">
              <button class="btn btn-primary" type="submit">{{ __("Save")}}</button>
            </div>
          </form>
        </div>
      </div>
      
    </div>
  </main>
@endsection 

resources/views/expense/index.blade.php
@extends('main')
@section('content')
  <main class="app-content">
    <div class="app-title">
      <div>
        <h1><i class="fa fa-dashboard"></i> {{ __("Expenses")}}</h1>
        <!-- <p>A free and open source Bootstrap 4 admin template</p> -->
      </div>
      <ul class="app-breadcrumb breadcrumb">
        <li class="breadcrumb-item"><i class="fa fa-home fa-lg"></i></li>
        <li class="breadcrumb-item"><a href="{{route('expenses.index')}}">{{ __("Expenses")}}</a></li>
      </ul>
    </div>
    <div class="row">
      <div class="col-md-12">
         @if(session('successMsg') != NULL)
          <div class="alert alert-success alert-dismissible fade show myalert" role="alert">
              <strong> ✅ SUCCESS!</strong>
              {{ session('successMsg') }}
              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
              </button>
          </div>
        @endif
        <div class="tile">
          <h3 class="tile-title d-inline-block">{{ __("Expense List")}}</h3>
          <a href="{{route('expenses.create')}}" class="btn btn-primary float-right"><i class="fa fa-plus" aria-hidden="true"></i> {{ __("Add New")}}</a>

           <div class="row">
              <div class="form-group col-md-3">
              <label for="InputStartDate">{{ __("Start Date")}}:</label>
              <input type="date" class="form-control" id="InputStartDate" name="start_date">
            </div>
            <div class="form-group col-md-3">
              <label for="InputEndDate">{{ __("End Date")}}:</label>
              <input type="date" class="form-control" id="InputEndDate" name="end_date">
            </div>
            @role('staff')
            <div class="form-group col-md-3">
              <label for="InputType">{{ __("Select Expense Type")}}:</label>
                <select class="js-example-basic-single" id="InputType" name="type">
                  <option value="">Choose Expensetype</option>
                    @foreach($expensetypes as $row)
                      <option value="{{$row->id}}" data-name="{{$row->name}}">{{$row->name}}</option>
                    @endforeach
                </select>
            </div>
            @endrole
            <div class="form-group col-md-3">
              <button class="btn btn-primary search_btn mt-4" type="button">{{ __("Search")}}</button>
            </div>
        </div>
          <div class="table-responsive">
            <table class="table table-bordered" id="expensetable">
              <thead>
                <tr>
                  <th>{{ __("#")}}</th>
                  <th>{{ __("Date")}}</th>
                  <th>{{ __("Amount")}}</th>
                  <th>{{ __("Type")}}</th>
                  <th>{{ __("Description")}}</th>
                  <th>{{ __("Actions")}}</th>
                </tr>
              </thead>
              <tbody>
                 @php $i=1; @endphp
                 @foreach($expenses as $row)
                <tr>
                  <td>{{$i++}}</td>
                  <td>{{Carbon\Carbon::parse($row->created_at)->format('d-m-Y')}}</td>
                  <td>{{number_format($row->amount)}}</td>
                  <td>{{$row->expense_type->name}}</td>
                  <td>{{$row->description}}</td>
                  <td>
                    {{-- @if($row->expense_type_id!=1) --}}
                    <a href="{{route('expenses.edit',$row->id)}}" class="btn btn-sm btn-warning">Edit</a>
                    {{-- @endif --}}
                    {{-- <form action="{{ route('expenses.destroy',$row->id) }}" method="POST" class="d-inline-block" onsubmit="return confirm('Are you sure?')">

                      @csrf
                      @method('DELETE')
                    <button type="submit" class="btn btn-danger">Delete</button>
                  </form> --}}
                  </td>
                </tr>
                @endforeach
              </tbody>
            </table>
          </div>
        </div>
      </div>
      
    </div>
  </main>
@endsection 
@section('script')
<script type="text/javascript">
  $(document).ready(function(){
    //alert("ok");
    setTimeout(function(){ $('.myalert').hide(); showDiv2() },3000);
    $('.js-example-basic-single').select2({width:'100%'});

     $('#expensetable').dataTable({
            "bPaginate": true,
            "bLengthChange": true,
            "bFilter": true,
            "bSort": true,
            "bInfo": true,
            "bAutoWidth": true,
            "bStateSave": true,
            "aoColumnDefs": [
                { 'bSortable': false, 'aTargets': [ -1,0] }
            ]
        });

      $('.search_btn').click(function () {
      //alert("ok");
        var sdate = $('#InputStartDate').val();
        var edate = $('#InputEndDate').val();
        var type_id=$("#InputType").val();

        $.ajaxSetup({
      headers: {
        'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
      }
    });
      //console.log(sdate, edate,type_id)
        var url="{{route('expensebytype')}}";
        var i=1;
         $('#expensetable').DataTable({
        "processing": true,
        "serverSide": true,
        destroy:true,
        "sort":false,
        "stateSave": true,
        "ajax": {
            url: url,
            type: "POST",
            data:{sdate:sdate,edate:edate,type_id:type_id},
            dataType:'json',
        },
        "columns": [
        {"data":'DT_RowIndex'},
        { "data": "created_at",
          sortable:false,
          render:function(data){
            return formatDate(data);
          }
        },
        { "data": null,
          render:function (data) {
            return thousands_separators(data.amount)
          }
        },
        { "data": "expense_type.name" },
        { "data": "description"},
        { "data": "id",
                    sortable:false,
                    render:function(data){
                      var routeurl="{{route('expenses.edit',':id')}}";
                      routeurl=routeurl.replace(':id',data);
                      return `<a class="btn btn-sm btn-warning " href="${routeurl}" data-id="${data}">Edit</a>`;
                    }
             }
        ],
       "info":false
    });
        
      })

    // Y/M/D into D/M/Y
    function formatDate (input) {
      var datePart = input.match(/\d+/g),
      year = datePart[0].substring(0,4), // get only two digits
      month = datePart[1], day = datePart[2];
      return day+'-'+month+'-'+year;
    }

    function thousands_separators(num){
      var num_parts = num.toString().split(".");
      num_parts[0] = num_parts[0].replace(/\B(?=(\d{3})+(?!\d))/g, ",");
      return num_parts.join(".");
    }
  })
  
</script>
@endsection