routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/','Auth\LoginController@showLoginForm');
//language
Route::get('lang/{locale}', 'LocalizationController@index')->name('lang');

Route::middleware('auth')->group(function () {
  Route::get('dashboard','MainController@dashboard')->name('dashboard');

  Route::get('getways', 'MainController@getways')->name('getways');
  
  Route::prefix('settings')->group(function () {
    // Settings => (cities, townships, statuses, expense_types, payment_types, banks)
    Route::resource('cities','CityController');
    Route::resource('townships','TownshipController');
    Route::resource('statuses','StatusController');
    Route::resource('expense_types','ExpenseTypeController');
    Route::resource('payment_types','PaymentTypeController');
    Route::resource('banks','BankController');
    Route::resource('sendergate','SenderGateController'); 
    Route::resource('senderoffice','SenderOfficeController');
  });

Route::post('expensebytype','ExpenseController@expensebytype')->name('expensebytype');
  // Success List
  Route::get('success_list','MainController@success_list')->name('success_list');

  // Reject List
  Route::get('reject_list','MainController@reject_list')->name('reject_list');
  Route::post('rejectitem','MainController@rejectitem')->name('rejectitem');


  // Return List
  Route::get('return_list','MainController@return_list')->name('return_list');
  Route::post('returnitem','MainController@returnitem')->name('returnitem');

  // Delay List
  Route::get('delay_list','MainController@delay_list')->name('delay_list');
  Route::get('delaycount','MainController@delaycount')->name('delaycount');

  // Financial Statement
  Route::get('statements','MainController@financial_statements')->name('statements');

  Route::post('successreport','MainController@successreport')->name('successreport');

  // Debt List
  Route::get('debt_list','MainController@debt_list')->name('debt_list');
  Route::get('debt_history','MainController@debt_history')->name('debt_history');

  Route::get('way_history','MainController@way_history')->name('way_history');
  Route::get('pickup_history','MainController@pickup_history')->name('pickup_history');
  Route::get('historydetails/{id}','MainController@historydetails')->name('historydetails');

  Route::get('debit/getdebitlistbyclient/{id}', 'MainController@getdebitlistbyclient')->name('debit.getdebitlistbyclient');
  Route::post('debit/getdebithistorybyclient', 'MainController@getdebithistorybyclient')->name('debit.getdebithistorybyclient');

  Route::post('getwayhistory','MainController@getwayhistory')->name('getwayhistory');
  Route::post('pickupbyclient','MainController@pickupbyclient')->name('pickupbyclient');
  Route::post('fix_debit', 'MainController@fix_debit')->name('fix_debit');

  Route::post('updateincome','MainController@updateincome')->name('updateincome');
  Route::post('incomesearch','MainController@incomesearch')->name('incomesearch');
  Route::post('waysreport','MainController@waysreport')->name('waysreport');
  Route::post('expensesearch','MainController@expensesearch')->name('expensesearch');
  Route::post('profit','MainController@profit')->name('profit');
  Route::get('banktransfer','MainController@banktransfer')->name('banktransfer');
  Route::post('transfer','MainController@transfer')->name('transfer.store');
  //pickupdone by delivery man
  Route::get('pickupdone/{id}/{qty}','MainController@pickupdone')->name('pickupdone');

  //amounta ad qty edit
  Route::post('editamountandqty','MainController@editamountandqty')->name('editamountandqty');

//normal
  Route::get('normal/{id}','MainController@normal')->name('normal');
  // staff
  Route::resource('staff','StaffController');

  //  For Staff


  // get schedules
  Route::resource('schedules', 'ScheduleController');
  // get assigned pickup
  Route::get('allpickup','ScheduleController@allpickup')->name('allpickup');
  // get assigned pickup noti
  Route::get('getnoti','ScheduleController@getnoti')->name('getnoti');


  // client
  Route::get('cancel', 'MainController@cancel')->name('cancel.index');
  Route::post('uploadfile', 'ScheduleController@uploadfile')->name('uploadfile');
  Route::post('storeandassignschedule', 'ScheduleController@storeandassignschedule')->name('schedules.storeandassign');

  Route::resource('items', 'ItemController');
  Route::get('newitem','ItemController@newitem')->name('newitem');
  Route::get('onway','ItemController@onway')->name('onway');
  Route::get('items/collectitem/{cid}/{pid}','ItemController@collectitem')->name('items.collect');
  Route::post('itemdetail','ItemController@itemdetail')->name('itemdetail');
  Route::post('wayassign','ItemController@assignWays')->name('wayassign');

  Route::get('checkitem/{pickupid}','ItemController@checkitem')->name('checkitem');
  Route::post('updateamount','ItemController@updateamount')->name('updateamount');
  
  Route::get('rejectnoti','MainController@rejectnoti')->name('rejectnoti');
  Route::get('clearrejectnoti/{id}','MainController@clearrejectnoti')->name('clearrejectnoti');
  Route::get('seennoti','MainController@seennoti')->name('seennoti');
  Route::post('updatewayassign','ItemController@updatewayassign')->name('updatewayassign');
  Route::post('townshipbystatus','ItemController@townshipbystatus')->name('townshipbystatus');
  Route::get('deletewayassign/{id}','ItemController@deletewayassign')->name('deletewayassign');


  Route::resource('clients', 'ClientController');
  Route::resource('delivery_men', 'DeliveryMenController');

  Route::get('incomes', 'MainController@incomes')->name('incomes');
  Route::get('incomes/addincomes', 'MainController@addincomeform')->name('incomes.create');
  Route::get('incomes/getsuccesswaysbydeliveryman/{id}', 'MainController@successways')->name('incomes.successways');
  Route::post('incomes/addincomes', 'MainController@addincomes')->name('incomes.store');
  Route::post('getitembyway', 'MainController@getitembyway')->name('getitembyway');
  Route::resource('expenses','ExpenseController');

  // For Client
  Route::get('pickups','MainController@pickups')->name('pickups');
  Route::post('pickups','MainController@donepickups')->name('donepickups');
  Route::post('delichargebytown','ItemController@delichargebytown')->name('delichargebytown');
  // Route::get('ways','MainController@ways')->name('ways');

  Route::prefix('ways')->group(function () {
    Route::get('pending','MainController@pending_ways')->name('pending_ways');
    Route::post('pending_deli_date','MainController@pending_deli_date')->name('pending_deli_date');
    Route::post('success_deli_date','MainController@success_deli_date')->name('success_deli_date');
    Route::post('reject_deli_date','MainController@reject_deli_date')->name('reject_deli_date');
    Route::get('reject','MainController@rejectwaybydeliveryman')->name('rejectwaybydeliveryman');
    Route::get('success','MainController@success_ways')->name('success_ways');
  });

  Route::post('waybydeliveryman','MainController@waybydeliveryman')->name('waybydeliveryman');
  Route::post('/createpdf', 'MainController@createpdf')->name('createpdf');

  Route::post('makeDelivered','MainController@makeDeliver')->name('makeDeliver');
  Route::post('retuenDeliver','MainController@retuenDeliver')->name('retuenDeliver');
  Route::post('rejectDeliver','MainController@rejectDeliver')->name('rejectDeliver');
  

});

Route::resource('profiles','ProfileController');

Auth::routes(['register'=>false]);

Route::get('/home', 'HomeController@index')->name('home');

app/DeliveryMan.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
class DeliveryMan extends Model
{
  use SoftDeletes;
  protected $fillable=[
  	'phone_no', 'address', 'user_id', 'city_id'
  ];

  public function user()
  {
    return $this->belongsTo('App\User');
  }

  public function city()
  {
    return $this->belongsTo('App\City');
  }

  public function townships(){
             return $this->belongsToMany('App\Township','delivery_man_township','delivery_men_id','township_id')
      ->withTimestamps();;
    }

  public function pickups()
  {
    return $this->hasMany('App\Pickup');
  }

  public function ways()
  {
    return $this->hasMany('App\Way');
  }
}

resources/views/deliveryman/create.blade.php
@extends('main')
@section('content')
  <main class="app-content">
    <div class="app-title">
      <div>
        <h1><i class="fa fa-dashboard"></i> {{ __("Delivery Men")}}</h1>
        <!-- <p>A free and open source Bootstrap 4 admin template</p> -->
      </div>
      <ul class="app-breadcrumb breadcrumb">
        <li class="breadcrumb-item"><i class="fa fa-home fa-lg"></i></li>
        <li class="breadcrumb-item"><a href="{{route('delivery_men.index')}}">{{ __("Delivery Men")}}</a></li>
      </ul>
    </div>
    <div class="row">
      <div class="col-md-12">
        <div class="tile">
          <h3 class="tile-title d-inline-block">Delivery Men Form</h3>
          
          <form action="{{route('delivery_men.store')}}" method="POST">
            @csrf
            <div class="form-group">
              <label for="deliname">{{ __("Name")}}:</label>
              <input class="form-control" id="deliname" type="text" placeholder="Enter name" name="name">
              <div class="form-control-feedback text-danger"> {{$errors->first('name') }} </div>
            </div>

            <div class="form-group">
              <label for="exampleInputEmail1">{{ __("Email address")}}</label>
              <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" name="email" placeholder="Enter email">
              <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
              <div class="form-control-feedback text-danger"> {{$errors->first('email') }} </div>
            </div>

            <div class="form-group">
              <label for="exampleInputPassword1">{{ __("Password")}}</label>
              <input type="password" class="form-control" id="exampleInputPassword1" name="password" placeholder="Enter Password">
              <div class="form-control-feedback text-danger"> {{$errors->first('password') }} </div>
            </div>

            <div class="form-group">
              <label for="password-confirm">{{ __("Confirm Password")}}</label>
               <input id="password-confirm" type="password" class="form-control" name="password_confirmation" required autocomplete="new-password">
              
            </div>

            <div class="form-group">
              <label for="phone">{{ __("Phone No")}}:</label>
              <input class="form-control" id="phone" type="text" placeholder="Enter Phone No" name="phone">
              <div class="form-control-feedback text-danger"> {{$errors->first('phone') }} </div>
            </div>

            <div class="form-group">
              <label for="address">{{ __("Address")}}:</label>
              <input class="form-control" id="address" type="text" placeholder="Enter Address" name="address">
              <div class="form-control-feedback text-danger"> {{$errors->first('address') }} </div>
            </div>

            <div class="form-group">
              <input type="checkbox" name="agent" class="agent" id="agentcheck">
              <label for="agentcheck">For agent</label>
            </div>

            <div class="form-group citydiv">
                <label for="township">{{ __("City")}}:</label>
                <select class="js-example-basic-multiple form-control" name="city" id="city">
                  <option>{{{ __("Choose City")}}}</option>
                  @foreach($cities as $row)
                  @if($row->name != "Yangon")
                  <option value="{{$row->id}}">{{$row->name}}</option>
                  @endif
                  @endforeach
                   
                </select>
            </div>

           <div class="form-group">
              <label for="township">{{ __("Delivery Townships")}}:</label>
              <select class="js-example-basic-multiple form-control" name="township[]" multiple="multiple" id="township">
                <option>{{{ __("Choose township")}}}</option>
                @foreach($townships as $row)
                <option value="{{$row->id}}">{{$row->name}}</option>
                @endforeach
                 
              </select>
              <div class="form-control-feedback text-danger"> {{$errors->first('townships') }} </div>
            </div>

            <div class="form-group">
              <button class="btn btn-primary" type="submit">{{ __("Save")}}</button>
            </div>
          </form>
        </div>
      </div>
      
    </div>
  </main>
@endsection 
@section('script')
<script type="text/javascript">
  $(document).ready(function() {
    $('.js-example-basic-multiple').select2();
    $('.citydiv').hide();

    $('.agent').click(function(){
        if ($('.agent').is(":checked"))
        {
          $('.citydiv').show();
        }else{
          $('.citydiv').hide();
        }
      })
   

  });
</script>
@endsection

resources/views/deliveryman/edit.blade.php
@extends('main')
@section('content')
  <main class="app-content">
    <div class="app-title">
      <div>
        <h1><i class="fa fa-dashboard"></i> {{ __("Delivery Men")}}</h1>
        <!-- <p>A free and open source Bootstrap 4 admin template</p> -->
      </div>
      <ul class="app-breadcrumb breadcrumb">
        <li class="breadcrumb-item"><i class="fa fa-home fa-lg"></i></li>
        <li class="breadcrumb-item"><a href="{{route('delivery_men.index')}}">{{ __("Delivery Men")}}</a></li>
      </ul>
    </div>
    <div class="row">
      <div class="col-md-12">
        <div class="tile">
          <h3 class="tile-title d-inline-block">Delivery Men Edit Form</h3>
          
          <form action="{{route('delivery_men.update',$deliveryMan->id)}}" method="POST">
            @csrf
            @method('PUT')
            <input type="hidden" name="oldpassword" value="{{$deliveryMan->user->password}}">
           <div class="form-group">
              <label for="InputCityName">{{ __("Name")}}:</label>
              <input class="form-control" id="InputCityName" type="text" placeholder="Enter name" name="name" value="{{$deliveryMan->user->name}}">
              <div class="form-control-feedback text-danger"> {{$errors->first('name') }} </div>
            </div>

            <div class="form-group">
              <label for="exampleInputEmail1">{{ __("Email address")}}</label>
              <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" name="email" placeholder="Enter email"value="{{$deliveryMan->user->email}}">
              <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
              <div class="form-control-feedback text-danger"> {{$errors->first('email') }} </div>
            </div>

            <div class="form-group">
              <input type="checkbox" class="mychangepsw" id="cpassw">
              <label for="cpassw">{{ __("Want to change password?")}}</label>
            </div>

            <div class="form-group psw">
              <label for="exampleInputPassword1">{{ __("Password")}}</label>
              <input type="password" class="form-control" id="exampleInputPassword1" name="password" placeholder="Enter Password">
              <div class="form-control-feedback text-danger"> {{$errors->first('password') }} </div>
            </div>

            <div class="form-group cpsw">
              <label for="password-confirm">{{ __("Confirm Password")}}</label>
               <input id="password-confirm" type="password" class="form-control" name="password_confirmation" autocomplete="new-password">
              
            </div>

            <div class="form-group">
              <label for="phone">{{ __("Phone No")}}:</label>
              <input class="form-control" id="phone" type="text" placeholder="Enter Phone No" name="phone" value="{{$deliveryMan->phone_no}}">
              <div class="form-control-feedback text-danger"> {{$errors->first('phone') }} </div>
            </div>

            <div class="form-group">
              <label for="address">{{ __("Address")}}:</label>
              <input class="form-control" id="address" type="text" placeholder="Enter Address" name="address" value="{{$deliveryMan->address}}">
              <div class="form-control-feedback text-danger"> {{$errors->first('address') }} </div>
            </div>

             <div class="form-group">
              <input type="checkbox" name="agent" class="agent" id="agentcheck" @if($deliveryMan->city_id != 1) checked="" @endif>
              <label for="agentcheck">For agent</label>
            </div>

            
            <div class="form-group citydiv">
                <label for="township">{{ __("City")}}:</label>
                <select class="js-example-basic-multiple form-control" name="city" >
                  <option>{{{ __("Choose City")}}}</option>
                  @foreach($cities as $row)
                  @if($row->name != "Yangon")
                  <option value="{{$row->id}}" @if($deliveryMan->city_id == $row->id) selected="selected" @endif>{{$row->name}}</option>
                  @endif
                  @endforeach
                   
                </select>
            </div>
            

            <div class="form-group">
              <label for="township">{{ __("Delivery Townships")}}:</label>
              @php
              $v = $deliveryMan->townships;
              @endphp
              <select class="js-example-basic-multiple form-control" name="township[]" multiple="multiple" id="township">
                <option>{{ __("Choose township")}}</option>
                @foreach($townships as $row)
                <option value="{{$row->id}}"  @foreach($v as $key=> $value)

                  @if($row->id==$value->pivot->township_id) {{"selected"}} @endif 
                  @endforeach>{{$row->name}}</option>
                @endforeach
                 
              </select>
              <div class="form-control-feedback text-danger"> {{$errors->first('townships') }} </div>
            </div>

            <div class="form-group">
              <button class="btn btn-primary" type="submit">{{ __("Save")}}</button>
            </div>
          </form>
        </div>
      </div>
      
    </div>
  </main>
@endsection 
@section('script')
<script type="text/javascript">
  $(document).ready(function(){
    $('.js-example-basic-multiple').select2();


    $(".psw").hide();
    $(".cpsw").hide();
    $(".mychangepsw").click(function(){
      if(this.checked){
    $(".psw").show();
    $(".cpsw").show();
      }else{
      $(".psw").hide();
    $(".cpsw").hide();
      }
    })
    
     if ($('.agent').is(":checked"))
      {
        $('.citydiv').show();
      }else{
        $('.citydiv').hide();
      }


    $('.agent').click(function(){
        if ($('.agent').is(":checked"))
        {
          $('.citydiv').show();
        }else{
          $('.citydiv').hide();
        }
      })
  })
</script>
@endsection

resources/views/deliveryman/index.blade.php
@extends('main')
@section('content')
  <main class="app-content">
    <div class="app-title">
      <div>
        <h1><i class="fa fa-dashboard"></i> {{ __("Delivery Men")}}</h1>
        <!-- <p>A free and open source Bootstrap 4 admin template</p> -->
      </div>
      <ul class="app-breadcrumb breadcrumb">
        <li class="breadcrumb-item"><i class="fa fa-home fa-lg"></i></li>
        <li class="breadcrumb-item"><a href="{{route('delivery_men.index')}}">{{ __("Delivery Men")}}</a></li>
      </ul>
    </div>
    <div class="row">
      <div class="col-md-12">
         @if(session('successMsg') != NULL)
              <div class="alert alert-success alert-dismissible fade show myalert" role="alert">
                  <strong> ✅ SUCCESS!</strong>
                  {{ session('successMsg') }}
                  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                  </button>
              </div>
          @endif
        <div class="tile">
          <h3 class="tile-title d-inline-block">{{ __("Delivery Men List")}}</h3>
          <a href="{{route('delivery_men.create')}}" class="btn btn-primary float-right"><i class="fa fa-plus" aria-hidden="true"></i> {{ __("Add New")}}</a>
          <div class="table-responsive">
            <table class="table dataTable">
              <thead>
                <tr>
                  <th>{{ __("#")}}</th>
                  <th>{{ __("Name")}}</th>
                  <th>{{ __("Phone No")}}</th>
                  <th>{{ __("Address")}}</th>
                  <th>{{ __("Townships")}}</th>
                  <th>{{ __("Actions")}}</th>
                </tr>
              </thead>
              <tbody>
                @php $i=1; @endphp
                @foreach($DeliveryMen as $row)
                <tr>
                  <td>{{$i++}}</td>
                  <td>{{$row->user->name}}</td>
                  <td>{{$row->phone_no}}</td>
                  <td>{{$row->address}}</td>
                  <td>
                    @foreach($row->townships as $township)
                      <span class="badge badge-info">{{$township->name}}</span>
                    @endforeach
                  </td>
                  <td>
                    <a href="{{route('delivery_men.edit',$row->id)}}" class="btn btn-warning">{{ __("Edit")}}</a>
                    <form action="{{ route('delivery_men.destroy',$row->id) }}" method="POST" class="d-inline-block" onsubmit="return confirm('Are you sure?')">

                      @csrf
                      @method('DELETE')
                    <button type="submit" class="btn btn-danger">{{ __("Delete")}}</button>
                  </form>
                  </td>
                </tr>
                @endforeach
              </tbody>
            </table>
          </div>
        </div>
      </div>
      
    </div>
  </main>
@endsection 
@section('script')
<script type="text/javascript">
  $(document).ready(function(){
    //alert("ok");
    setTimeout(function(){ $('.myalert').hide(); showDiv2() },3000);
  })
  
</script>
@endsection