routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/','Auth\LoginController@showLoginForm');
//language
Route::get('lang/{locale}', 'LocalizationController@index')->name('lang');

Route::middleware('auth')->group(function () {
  Route::get('dashboard','MainController@dashboard')->name('dashboard');

  Route::get('getways', 'MainController@getways')->name('getways');
  
  Route::prefix('settings')->group(function () {
    // Settings => (cities, townships, statuses, expense_types, payment_types, banks)
    Route::resource('cities','CityController');
    Route::resource('townships','TownshipController');
    Route::resource('statuses','StatusController');
    Route::resource('expense_types','ExpenseTypeController');
    Route::resource('payment_types','PaymentTypeController');
    Route::resource('banks','BankController');
    Route::resource('sendergate','SenderGateController'); 
    Route::resource('senderoffice','SenderOfficeController');
  });

Route::post('expensebytype','ExpenseController@expensebytype')->name('expensebytype');
  // Success List
  Route::get('success_list','MainController@success_list')->name('success_list');

  // Reject List
  Route::get('reject_list','MainController@reject_list')->name('reject_list');
  Route::post('rejectitem','MainController@rejectitem')->name('rejectitem');


  // Return List
  Route::get('return_list','MainController@return_list')->name('return_list');
  Route::post('returnitem','MainController@returnitem')->name('returnitem');

  // Delay List
  Route::get('delay_list','MainController@delay_list')->name('delay_list');
  Route::get('delaycount','MainController@delaycount')->name('delaycount');

  // Financial Statement
  Route::get('statements','MainController@financial_statements')->name('statements');

  Route::post('successreport','MainController@successreport')->name('successreport');

  // Debt List
  Route::get('debt_list','MainController@debt_list')->name('debt_list');
  Route::get('debt_history','MainController@debt_history')->name('debt_history');

  Route::get('way_history','MainController@way_history')->name('way_history');
  Route::get('pickup_history','MainController@pickup_history')->name('pickup_history');
  Route::get('historydetails/{id}','MainController@historydetails')->name('historydetails');

  Route::get('debit/getdebitlistbyclient/{id}', 'MainController@getdebitlistbyclient')->name('debit.getdebitlistbyclient');
  Route::post('debit/getdebithistorybyclient', 'MainController@getdebithistorybyclient')->name('debit.getdebithistorybyclient');

  Route::post('getwayhistory','MainController@getwayhistory')->name('getwayhistory');
  Route::post('pickupbyclient','MainController@pickupbyclient')->name('pickupbyclient');
  Route::post('fix_debit', 'MainController@fix_debit')->name('fix_debit');

  Route::post('updateincome','MainController@updateincome')->name('updateincome');
  Route::post('incomesearch','MainController@incomesearch')->name('incomesearch');
  Route::post('waysreport','MainController@waysreport')->name('waysreport');
  Route::post('expensesearch','MainController@expensesearch')->name('expensesearch');
  Route::post('profit','MainController@profit')->name('profit');
  Route::get('banktransfer','MainController@banktransfer')->name('banktransfer');
  Route::post('transfer','MainController@transfer')->name('transfer.store');
  //pickupdone by delivery man
  Route::get('pickupdone/{id}/{qty}','MainController@pickupdone')->name('pickupdone');

  //amounta ad qty edit
  Route::post('editamountandqty','MainController@editamountandqty')->name('editamountandqty');

//normal
  Route::get('normal/{id}','MainController@normal')->name('normal');
  // staff
  Route::resource('staff','StaffController');

  //  For Staff


  // get schedules
  Route::resource('schedules', 'ScheduleController');
  // get assigned pickup
  Route::get('allpickup','ScheduleController@allpickup')->name('allpickup');
  // get assigned pickup noti
  Route::get('getnoti','ScheduleController@getnoti')->name('getnoti');


  // client
  Route::get('cancel', 'MainController@cancel')->name('cancel.index');
  Route::post('uploadfile', 'ScheduleController@uploadfile')->name('uploadfile');
  Route::post('storeandassignschedule', 'ScheduleController@storeandassignschedule')->name('schedules.storeandassign');

  Route::resource('items', 'ItemController');
  Route::get('newitem','ItemController@newitem')->name('newitem');
  Route::get('onway','ItemController@onway')->name('onway');
  Route::get('items/collectitem/{cid}/{pid}','ItemController@collectitem')->name('items.collect');
  Route::post('itemdetail','ItemController@itemdetail')->name('itemdetail');
  Route::post('wayassign','ItemController@assignWays')->name('wayassign');

  Route::get('checkitem/{pickupid}','ItemController@checkitem')->name('checkitem');
  Route::post('updateamount','ItemController@updateamount')->name('updateamount');
  
  Route::get('rejectnoti','MainController@rejectnoti')->name('rejectnoti');
  Route::get('clearrejectnoti/{id}','MainController@clearrejectnoti')->name('clearrejectnoti');
  Route::get('seennoti','MainController@seennoti')->name('seennoti');
  Route::post('updatewayassign','ItemController@updatewayassign')->name('updatewayassign');
  Route::post('townshipbystatus','ItemController@townshipbystatus')->name('townshipbystatus');
  Route::get('deletewayassign/{id}','ItemController@deletewayassign')->name('deletewayassign');


  Route::resource('clients', 'ClientController');
  Route::resource('delivery_men', 'DeliveryMenController');

  Route::get('incomes', 'MainController@incomes')->name('incomes');
  Route::get('incomes/addincomes', 'MainController@addincomeform')->name('incomes.create');
  Route::get('incomes/getsuccesswaysbydeliveryman/{id}', 'MainController@successways')->name('incomes.successways');
  Route::post('incomes/addincomes', 'MainController@addincomes')->name('incomes.store');
  Route::post('getitembyway', 'MainController@getitembyway')->name('getitembyway');
  Route::resource('expenses','ExpenseController');

  // For Client
  Route::get('pickups','MainController@pickups')->name('pickups');
  Route::post('pickups','MainController@donepickups')->name('donepickups');
  Route::post('delichargebytown','ItemController@delichargebytown')->name('delichargebytown');
  // Route::get('ways','MainController@ways')->name('ways');

  Route::prefix('ways')->group(function () {
    Route::get('pending','MainController@pending_ways')->name('pending_ways');
    Route::post('pending_deli_date','MainController@pending_deli_date')->name('pending_deli_date');
    Route::post('success_deli_date','MainController@success_deli_date')->name('success_deli_date');
    Route::post('reject_deli_date','MainController@reject_deli_date')->name('reject_deli_date');
    Route::get('reject','MainController@rejectwaybydeliveryman')->name('rejectwaybydeliveryman');
    Route::get('success','MainController@success_ways')->name('success_ways');
  });

  Route::post('waybydeliveryman','MainController@waybydeliveryman')->name('waybydeliveryman');
  Route::post('/createpdf', 'MainController@createpdf')->name('createpdf');

  Route::post('makeDelivered','MainController@makeDeliver')->name('makeDeliver');
  Route::post('retuenDeliver','MainController@retuenDeliver')->name('retuenDeliver');
  Route::post('rejectDeliver','MainController@rejectDeliver')->name('rejectDeliver');
  

});

Route::resource('profiles','ProfileController');

Auth::routes(['register'=>false]);

Route::get('/home', 'HomeController@index')->name('home');

app/Client.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Client extends Model
{
  use SoftDeletes;
  protected $fillable=[
  	'contact_person', 'phone_no', 'address', 'codeno', 'user_id', 'township_id','account','owner'
  ];

  public function user()
  {
    return $this->belongsTo('App\User');
  }

  public function township()
  {
    return $this->belongsTo('App\Township');
  }

  public function schedules()
  {
    return $this->hasMany('App\Schedule');
  }
}

app/Http/Controllers/ClientController.php
<?php

namespace App\Http\Controllers;

use App\Client;
use App\Township;
use Illuminate\Http\Request;
use Carbon;
use App\User;
use Illuminate\Support\Facades\Hash;

class ClientController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $clients=Client::all();
        return view('client.index',compact('clients'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

        $townships=Township::all();
        return view('client.create',compact('townships'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $mytime = Carbon\Carbon::now();
        $array = explode('-', $mytime->toDateString());
        $codeno=$array[0].$array[1]."001";
        $latestdata=Client::whereMonth('created_at',Carbon\Carbon::today())->orderBy('id','desc')->first();
            //dd($latecodeno);
         $validator = $request->validate([
            'name'  => ['required', 'string', 'max:255'],
            'email'  => ['required','string','email','max:255','unique:users'],
            'password'  => ['required','min:6','confirmed'],
            'phone'  => ['required'],
            'address'  => ['required','string'],
            'person'=>['required','string'],
            'township'=>['required'],
           
        ]);
        if($validator){
            
            $user = new User;
            $user->name = $request->name;
            $user->email = $request->email;
            $user->password = Hash::make($request->password);
            $user->save();
            $user->assignRole('client');
            $client=new Client;
            $client->phone_no =$request->phone;
            $client->address = $request->address;
            $client->account=$request->account;
            $client->owner=$request->owner;
            $client->contact_person = $request->person;
            if(!$latestdata){
             $client->codeno=$codeno;   
         }else{
            
            $latecodeno=$latestdata->codeno;
            $client->codeno=$latecodeno+1;
         }
            
            $client->township_id = $request->township;
            $client->user_id = $user->id;
            $client->save();
           
            return redirect()->route('clients.index')->with("successMsg",'New Client is ADDED in your data');
        }
        else
        {
            return redirect::back()->withErrors($validator);
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Client  $client
     * @return \Illuminate\Http\Response
     */
    public function show(Client $client)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Client  $client
     * @return \Illuminate\Http\Response
     */
    public function edit(Client $client)
    {
        $townships=Township::all();
        $client=$client;
        return view('client.edit',compact('client','townships'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Client  $client
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Client $client)
    {
        $validator = $request->validate([
            'name'  => ['required', 'string', 'max:255'],
            'email'  => ['required','string','email','max:255'],
            'phone'  => ['required'],
            'address'  => ['required','string'],
            'person'=>['required','string'],
            'township'=>['required'],
           
        ]);
         //dd($request);
        if($validator){
            $client=$client;
            $user =User::find($client->user_id);
            $user->name = $request->name;
            $user->email = $request->email;
            if($request->password!=null){
              $user->password = Hash::make($request->password);   
          }else{
              $user->password = $request->oldpassword;
          }
           
            $user->save();
            
            $client->phone_no =$request->phone;
            $client->address = $request->address;
            $client->account=$request->account;
            $client->owner=$request->owner;
            $client->contact_person = $request->person;
            $client->township_id = $request->township;
            $client->user_id = $user->id;
            $client->save();
           
            return redirect()->route('clients.index')->with("successMsg",'Update Successfully');
        }
        else
        {
            return redirect::back()->withErrors($validator);
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Client  $client
     * @return \Illuminate\Http\Response
     */
    public function destroy(Client $client)
    {
        $client=$client;
        $user =User::find($client->user_id);
        $user->delete();
        $client->delete();
       return redirect()->route('clients.index')->with('successMsg','Existing Client is DELETED in your data');
    }
}

resources/views/client/create.blade.php
@extends('main')
@section('content')
  <main class="app-content">
    <div class="app-title">
      <div>
        <h1><i class="fa fa-dashboard"></i> Clients</h1>
        <!-- <p>A free and open source Bootstrap 4 admin template</p> -->
      </div>
      <ul class="app-breadcrumb breadcrumb">
        <li class="breadcrumb-item"><i class="fa fa-home fa-lg"></i></li>
        <li class="breadcrumb-item"><a href="{{route('clients.index')}}">Clients</a></li>
      </ul>
    </div>
    <div class="row">
      <div class="col-md-12">
        <div class="tile">
          <h3 class="tile-title d-inline-block">Client Create Form</h3>    
          <form action="{{route('clients.store')}}" method="POST">
            @csrf
            <div class="form-group">
              <label for="InputCityName">Name:</label>
              <input class="form-control" id="InputCityName" type="text" placeholder="Enter name" name="name">
              <div class="form-control-feedback text-danger"> {{$errors->first('name') }} </div>
            </div>

            <div class="form-group">
              <label for="exampleInputEmail1">Email address</label>
              <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" name="email" placeholder="Enter email">
              <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
              <div class="form-control-feedback text-danger"> {{$errors->first('email') }} </div>
            </div>

            <div class="form-group">
              <label for="exampleInputPassword1">Password</label>
              <input type="password" class="form-control" id="exampleInputPassword1" name="password" placeholder="Enter Password">
              <div class="form-control-feedback text-danger"> {{$errors->first('password') }} </div>
            </div>

            <div class="form-group">
              <label for="password-confirm">Confirm Password</label>
               <input id="password-confirm" type="password" class="form-control" name="password_confirmation" required autocomplete="new-password">
              
            </div>

            <div class="form-group">
              <label for="phone">Phone No:</label>
              <input class="form-control" id="phone" type="text" placeholder="Enter Phone No" name="phone">
              <div class="form-control-feedback text-danger"> {{$errors->first('phone') }} </div>
            </div>

            <div class="form-group">
              <label for="address">Address:</label>
              <input class="form-control" id="address" type="text" placeholder="Enter Address" name="address">
              <div class="form-control-feedback text-danger"> {{$errors->first('address') }} </div>
            </div>

             <div class="form-group">
              <label for="account">Bank Account:</label>
              <input class="form-control" id="account" type="text" placeholder="Enter Bank Account" name="account">
              <div class="form-control-feedback text-danger"> {{$errors->first('account') }} </div>
            </div>

             <div class="form-group">
              <label for="owner">Bank Acccount Owner:</label>
              <input class="form-control" id="owner" type="text" name="owner" placeholder="enter bank acccount owner">
              <div class="form-control-feedback text-danger"> {{$errors->first('owner') }} </div>
            </div>

            <div class="form-group">
              <label for="contactp">Contact Person:</label>
              <input class="form-control" id="contactp" type="text" name="person" placeholder="enter contact person">
              <div class="form-control-feedback text-danger"> {{$errors->first('person') }} </div>
            </div>

            <div class="form-group">
              <label for="township">Township</label>
              <select class="form-control" id="township" name="township">
                <option>Choose Township</option>
                @foreach($townships as $row)
                <option value="{{$row->id}}">{{$row->name}}</option>
                @endforeach
              </select>
              <div class="form-control-feedback text-danger"> {{$errors->first('township') }} </div>
            </div>

            <div class="form-group">
              <button class="btn btn-primary" type="submit">Save</button>
            </div>
          </form>
        </div>
      </div>
      
    </div>
  </main>
@endsection 

resources/views/client/edit.blade.php
@extends('main')
@section('content')
  <main class="app-content">
    <div class="app-title">
      <div>
        <h1><i class="fa fa-dashboard"></i> Clients</h1>
        <!-- <p>A free and open source Bootstrap 4 admin template</p> -->
      </div>
      <ul class="app-breadcrumb breadcrumb">
        <li class="breadcrumb-item"><i class="fa fa-home fa-lg"></i></li>
        <li class="breadcrumb-item"><a href="{{route('clients.index')}}">Clients</a></li>
      </ul>
    </div>
    <div class="row">
      <div class="col-md-12">
        <div class="tile">
          <h3 class="tile-title d-inline-block">Client Edit Form</h3>
          
          <form action="{{route('clients.update',$client->id)}}" method="POST">
            @csrf
            @method('PUT')
            <input type="hidden" name="oldpassword" value="{{$client->user->password}}">
           <div class="form-group">
              <label for="InputCityName">Name:</label>
              <input class="form-control" id="InputCityName" type="text" placeholder="Enter name" name="name" value="{{$client->user->name}}">
              <div class="form-control-feedback text-danger"> {{$errors->first('name') }} </div>
            </div>

            <div class="form-group">
              <label for="exampleInputEmail1">Email address</label>
              <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" name="email" placeholder="Enter email"value="{{$client->user->email}}">
              <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
              <div class="form-control-feedback text-danger"> {{$errors->first('email') }} </div>
            </div>

            <div class="form-group">
              <input type="checkbox" class="mychangepsw" id="cpassw">
              <label for="cpassw">Want to change password?</label>
            </div>

            <div class="form-group psw">
              <label for="exampleInputPassword1">Password</label>
              <input type="password" class="form-control" id="exampleInputPassword1" name="password" placeholder="Enter Password">
              <div class="form-control-feedback text-danger"> {{$errors->first('password') }} </div>
            </div>

            <div class="form-group cpsw">
              <label for="password-confirm">Confirm Password</label>
               <input id="password-confirm" type="password" class="form-control" name="password_confirmation" autocomplete="new-password">
              
            </div>

            <div class="form-group">
              <label for="phone">Phone No:</label>
              <input class="form-control" id="phone" type="text" placeholder="Enter Phone No" name="phone" value="{{$client->phone_no}}">
              <div class="form-control-feedback text-danger"> {{$errors->first('phone') }} </div>
            </div>

            <div class="form-group">
              <label for="address">Address:</label>
              <input class="form-control" id="address" type="text" placeholder="Enter Address" name="address" value="{{$client->address}}">
              <div class="form-control-feedback text-danger"> {{$errors->first('address') }} </div>
            </div>


             <div class="form-group">
              <label for="account">Bank Account:</label>
              <input class="form-control" id="account" type="text" placeholder="Enter Bank Account" name="account" value="{{$client->account}}">
              <div class="form-control-feedback text-danger"> {{$errors->first('account') }} </div>
            </div>

             <div class="form-group">
              <label for="owner">Bank Acccount Owner:</label>
              <input class="form-control" id="owner" type="text" name="owner" placeholder="enter bank acccount owner" value="{{$client->owner}}">
              <div class="form-control-feedback text-danger"> {{$errors->first('owner') }} </div>
            </div>
           <div class="form-group">
              <label for="contactp">Contact Person:</label>
              <input class="form-control" id="contactp" type="text" name="person" placeholder="enter contact person" value="{{$client->contact_person}}">
              <div class="form-control-feedback text-danger"> {{$errors->first('person') }} </div>
            </div>

            <div class="form-group">
              <label for="township">Township</label>
              <select class="form-control" id="township" name="township">
                <option>Choose Township</option>
                @foreach($townships as $row)
                <option value="{{$row->id}}" @if($client->township_id==$row->id) selected @endif>{{$row->name}}</option>
                @endforeach
              </select>
              <div class="form-control-feedback text-danger"> {{$errors->first('township') }} </div>
            </div>

            <div class="form-group">
              <button class="btn btn-primary" type="submit">Save</button>
            </div>
          </form>
        </div>
      </div>
      
    </div>
  </main>
@endsection 
@section('script')
<script type="text/javascript">
  $(document).ready(function(){
    $(".psw").hide();
    $(".cpsw").hide();
    $(".mychangepsw").click(function(){
      if(this.checked){
    $(".psw").show();
    $(".cpsw").show();
      }else{
      $(".psw").hide();
    $(".cpsw").hide();
      }
    })
  })
</script>
@endsection

resources/views/client/index.blade.php
@extends('main')
@section('content')
  <main class="app-content">
    <div class="app-title">
      <div>
        <h1><i class="fa fa-dashboard"></i> Clients</h1>
        <!-- <p>A free and open source Bootstrap 4 admin template</p> -->
      </div>
      <ul class="app-breadcrumb breadcrumb">
        <li class="breadcrumb-item"><i class="fa fa-home fa-lg"></i></li>
        <li class="breadcrumb-item"><a href="{{route('clients.index')}}">Clients</a></li>
      </ul>
    </div>
    <div class="row">
      <div class="col-md-12">
        @if(session('successMsg') != NULL)
          <div class="alert alert-success alert-dismissible fade show myalert" role="alert">
              <strong> ✅ SUCCESS!</strong>
              {{ session('successMsg') }}
              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
              </button>
          </div>
        @endif
        <div class="tile">
          <h3 class="tile-title d-inline-block">Clients List</h3>
          <a href="{{route('clients.create')}}" class="btn btn-primary float-right"><i class="fa fa-plus" aria-hidden="true"></i> Add New</a>
          <div class="table-responsive">
            <table class="table" id="dataTable">
              <thead>
                <tr>
                  <th>#</th>
                  <th>{{ __('Name')}}</th>
                  <th>{{ __('Phone No')}}</th>
                  <th>{{ __('Address')}}</th>
                  <th>{{ __('Contact_Person')}}</th>
                  <th>{{ __('Township')}}</th>
                  <th>{{ __('Bank Owner and Acccount')}}</th>
                  <th>Actions</th>
                </tr>
              </thead>
              <tbody>
                @php $i=1; @endphp
                @foreach($clients as $row)
                <tr>
                  <td>{{$i++}}</td>
                  <td>{{$row->user->name}}</td>
                  <td>{{$row->phone_no}}</td>
                  <td>{{$row->address}}</td>
                  <td>{{$row->contact_person}}</td>
                  <td>{{$row->township->name}}</td>
                  <td>{{$row->owner}}({{$row->account}})</td>
                  <td>
                    <a href="{{route('clients.edit',$row->id)}}" class="btn btn-warning">Edit</a>
                    <form action="{{ route('clients.destroy',$row->id) }}" method="POST" class="d-inline-block" onsubmit="return confirm('Are you sure?')">

                      @csrf
                      @method('DELETE')
                    <button type="submit" class="btn btn-danger">Delete</button>
                  </form>
                  </td>
                </tr>
                @endforeach
              </tbody>
            </table>
          </div>
        </div>
      </div>
      
    </div>
  </main>
@endsection 
@section('script')
<script type="text/javascript">
  $(document).ready(function(){
    //alert("ok");
    setTimeout(function(){ $('.myalert').hide(); showDiv2() },3000);

    // Call the dataTables jQuery plugin
    $('#dataTable').DataTable( {
      "aaSorting": [[1,'asc']]
    });
  })
  
</script>
@endsection